### ISSUE TITLE
The content isn't showing on the screen

### ISSUE THREAD

**Issue by Sophia-Villamayor** [Sophia-Villamayor/call-to-action-banner#1]
@Thomasjbradley @MacKenzieRose
The code is responsive with my css, however, it doesn't appear on the website.

**Comment by MacKenzieRose** [comment]
@Sophia-Villamayor 

If you take the position and transform stylings off of your text and picture classes in your css file (lines 35, 36, 53, and 54) you'll see your content start to appear. It's currently positioned such that the overflow value is hiding all of it.

Because Markbot needs position and transform for this assignment, you might think about applying those to your content class instead. 

Cheers!

MacKenzie

**Comment by MacKenzieRose** [comment]
If this issue has been resolved, feel free to close it :)

Cheers!
MacKenzie
